baseURL = "https://labveiltech.redoxdigital.ch/"
languageCode = "fr-ch"
title = "Le blog de Mikael"
themesDir = "themes"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 5
canonifyURLs = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addFrame = true
  addDot = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

[menu]
  [[menu.main]]
    identifier = 'categories'
    name = 'Catégories'
    url = '/categories/'
    weight = 1

  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    weight = 2